params:
    epochs: 3
    batch_size: 32
    no_classes: 10
    input_shape: [28.28]
    losss_function: sparse_categorical_crossentropy
    metrics: accuracy
    optimizer: SGD
    validation_datasize: 50000

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plot_dir: plots
  plot_name: plot.png
  chekpoints_dir: checkpoints
  model_name: model.h5        #default model name
  
logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs  

  