params:
    epochs: 30
    batch_size: 32
    no_classes: 10
    input_shape: [28.28]
    losss_function: sparse_categorical_crossentropy
    metrics: accuracy
    optimizer: SGD
    validation_datasize: 50000

artifacts:
  artifacts_dir: artifacts
  model_dr: model
  plot_dir: plots
  chekpoints_dir: checkpoints
  
logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs  

  